### PR TITLE
Rules: Failed rule run logs a useful error message

### LINKED ISSUE #115: Rules: Logged error on failed rule run doesn‘t contain any error information
## Expected Behavior
I would expect that the logged message includes a detailed error message like the following:
```
org.openhab.core.items.ItemNotFoundException: Item 'Aussenlicht' could not be found in the item registry
```

## Current Behavior
When a JSRule run failes, a message like that is logged:
```
2022-05-16 22:31:24.256 [ERROR] [e.automation.internal.RuleEngineImpl] - Failed to execute rule 'Test-Rule-2c1e38ee-dec4-432f-b0ab-cd3192361c04': Fail to execute action: 1
```

## Possible Solution

I think I already have some solution, but this required additional testing.
I will soon open a PR.

## Steps to Reproduce (for Bugs)

1. Create a JSRule that will produce an error, e.g. by using `items.getItem()` on a non existing Item.
2. Run the rule.

## Your Environment

* Version used: (e.g., openHAB and **JS Scripting add-on version**): openHAB 3.3.0.M5
* openhab-js version used: 1.2.3

### PR DESCRIPTION
**Pull request by florian-h05**
Fixes #115.

When a rule run fails, now the JavaScript error is logged (instead of the useless `Failed to execute action: 1` from before), which looks like:
```
2022-05-17 13:59:21.285 [ERROR] [enhab.automation.script.file.test.js] - Failed to execute rule Test-Rule-73bd4126-38b7-4ce7-97bb-98aa4cafa0b5: org.openhab.core.items.ItemNotFoundException: Item 'Aussenlicht' could not be found in the item registry
```

Signed-off-by: Florian Hotze <florianh_dev@icloud.com>

### CODE REVIEW

**Comment by jpg0** [comment]
Great work, this has annoyed me for a long time!

**Comment by florian-h05** [comment]
Yeah, this makes script debugging possible from now on.
Can you merge?

**Comment by jpg0** [comment]
The only question I have regarding merging is whether swallowing the exception (rather than rethrowing it after logging it) causes any other changes. For example does this mean that openHAB would think that the rule ran successfully even though it didn't? In that case would it be better to log and rethrow?

**Comment by florian-h05** [comment]
You are absolutely right with your thoughts, I do not know whether this will cause any problems, so I will rethrow.

File: rules/rules.js [hunk 1]
```diff
@@ -207,11 +207,19 @@ let JSRule = function (ruleConfig) {
...
+        return ruleConfig.execute(getTriggeredData(input));
+      } catch (error) {
+        // logging error is required for meaningful error log message
+        // when throwing error: error is caught by core framework and no meaningful message is logged
+        if (error.stack) {
+          console.error(`Failed to execute rule ${ruid}: ${error}: ${error.stack}`);
+          throw Error(`Failed to execute rule ${ruid}: ${error}: ${error.stack}`);
+        } else {
+          console.error(`Failed to execute rule ${ruid}: ${error}`);
+          throw Error(`Failed to execute rule ${ruid}: ${error}`);
```
Comment (jpg0) [inline rules/rules.js:220]: Would it be cleaner to:

```
let msg = `Failed to execute rule ${ruid}: ${error} ${error.stack ? ": " + error.stack : "" }`
console.error(msg);
throw Error(msg);
```

So that you don't need to repeat the message so many times?
