### PR TITLE
[rules] Fix `itemName` & `triggerType` unavailable for Group in Item****Triggers

### LINKED ISSUE #145: [rules] ItemStateChangeTrigger event data incorrect if the Item is a Group.
**ItemStateChangeTrigger** event data incorrect if the Item is a Group.  
It appears that rules.js/getTriggeredData() does not handle the case when the triggered Item is a Group.

https://www.openhab.org/docs/configuration/items.html#groups

When using a Group Item the event **triggerType** and **itemName** are missing and the event class is **org.openhab.core.items.events.GroupItemStateChangedEvent** instead of **org.openhab.core.items.events.ItemStateChangedEvent**.

I have included test code to reproduce below.

```
Group:Switch:OR(ON,OFF) g2 
Switch b1 "test b1" (g2)
Switch b2 "test b2" (g2)
Switch b3 "test b3" (g2)
```

```
rules.JSRule({
    name: "Event Trigger Test",
    description: "When state of group changes log event details"
    triggers: [
        triggers.ItemStateChangeTrigger('g2', 'OFF', 'ON'),
        triggers.ItemStateChangeTrigger('b1', 'OFF', 'ON')
    ],
    execute: event => {
        console.log(event);
    }
});
```

```
2022-07-02 09:16:18.563 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'b1' received command ON
2022-07-02 09:16:18.572 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'b1' changed from OFF to ON
2022-07-02 09:16:18.594 [INFO ] [hab.event.GroupItemStateChangedEvent] - Item 'g2' changed from OFF to ON through b1
2022-07-02 09:16:18.623 [INFO ] [enhab.automation.script.file.test.js] - {
  "oldState": "OFF",
  "newState": "ON",
  "itemName": "b1",
  "eventType": "change",
  "triggerType": "ItemStateChangeTrigger",
  "eventClass": "org.openhab.core.items.events.ItemStateChangedEvent",
  "payload": {
    "type": "OnOff",
    "value": "ON",
    "oldType": "OnOff",
    "oldValue": "OFF"
  },
  "module": "18dd392e-28f5-4286-9f52-552dd8c8cc0e"
}

2022-07-02 09:16:18.634 [INFO ] [enhab.automation.script.file.test.js] - {
  "oldState": "OFF",
  "newState": "ON",
  "eventClass": "org.openhab.core.items.events.GroupItemStateChangedEvent",
  "payload": {
    "type": "OnOff",
    "value": "ON",
    "oldType": "OnOff",
    "oldValue": "OFF"
  },
  "module": "aa2b5da4-2a51-431a-87d2-b622a90753b8"
}
```

_Originally posted by @rickoman in https://github.com/openhab/openhab-js/issues/136#issuecomment-1172928136_

### PR DESCRIPTION
**Pull request by florian-h05**
Fixes #145: Item****Trigger event data incorrect if the Item is a Group.

Signed-off-by: Florian Hotze <florianh_dev@icloud.com>

### CODE REVIEW

File: rules/rules.js [hunk 1]
```diff
@@ -403,19 +403,24 @@ const getTriggeredData = function (input) {
 
   // Only with event data (for Item, Thing & Channel triggers)
   if (event) {
+    try {
+      data.itemName = event.getItemName();
+    } catch (e) {
+      // do nothing
+    }
     switch (Java.typeName(event.class)) {
+      case 'org.openhab.core.items.events.GroupItemCommandEvent':
```
Comment (digitaldan) [inline rules/rules.js:412]: Instead of the try/catch block, what about setting it in the case statement first without a break, so the statement falls through to the group/item logic ? 
```
      case 'org.openhab.core.items.events.ItemCommandEvent':
        data.itemName = event.getItemName();
        // no break here
      case 'org.openhab.core.items.events.GroupItemCommandEvent':
        data.itemName = event.getItemName();
        data.eventType = 'command';
        data.triggerType = 'ItemCommandTrigger';
        break;
```

Comment (florian-h05) [reply rules/rules.js:412]: I created the try catch block to add `itemName` every time it is available, but I am also comfortable with setting `itemName` in the switch statement.

**Comment by florian-h05** [comment]
Short reminder for myself: Update the changelog for this and the last PR.

File: rules/rules.js (hunk 1 above)
Comment (digitaldan) [reply rules/rules.js:412]: I'm ok either way, if i actually write the whole case statement out, it does get a little verbose, so maybe your way is better :-)  


```javascript
      case 'org.openhab.core.items.events.ItemCommandEvent':
         data.itemName = event.getItemName();
      case 'org.openhab.core.items.events.GroupItemCommandEvent':
        data.eventType = 'command';
        data.triggerType = 'ItemCommandTrigger';
        break;
      case 'org.openhab.core.items.events.ItemStateChangedEvent':
        data.itemName = event.getItemName();
      case 'org.openhab.core.items.events.GroupItemStateChangedEvent':
        data.eventType = 'change';
        data.triggerType = 'ItemStateChangeTrigger';
        break;
      case 'org.openhab.core.items.events.ItemStateEvent':
        data.itemName = event.getItemName();
      case 'org.openhab.core.items.events.GroupItemStateEvent':
        data.eventType = 'update';
        data.triggerType = 'ItemStateUpdateTrigger';
```

**Review by digitaldan — APPROVED** [review]
LGTM, feel free to merge if ready!
